### ISSUE TITLE
v2cat build issue

### ISSUE THREAD

**Issue by khevessy** [xweissada/vanetza#1]
I am trying to build v2cat application.
I am defining BUILD_V2CAT on command line (`cmake .. -DBUILD_V2CAT=ON`). When issuing `make` command, I am getting following error:
```
/home/user/vanetza-security/xweissada/vanetza/vanetza/security/hmac.cpp: In function ‘vanetza::security::KeyTag vanetza::security::create_hmac_tag(const ByteBuffer&, const HmacKey&)’:
/home/user/vanetza-security/xweissada/vanetza/vanetza/security/hmac.cpp:17:15: error: ‘byte’ is not a member of ‘CryptoPP’; did you mean ‘byte’?
   17 |     CryptoPP::byte tag[hmacKey.size()];
      |               ^~~~
In file included from /usr/include/cryptopp/osrng.h:9,
                 from /home/user/vanetza-security/xweissada/vanetza/vanetza/security/hmac.cpp:2:
/usr/include/cryptopp/config.h:203:23: note: ‘byte’ declared here
  203 | typedef unsigned char byte;  // put in global namespace to avoid ambiguity with other byte typedefs
      |                       ^~~~
/home/user/vanetza-security/xweissada/vanetza/vanetza/security/hmac.cpp:19:15: error: ‘tag’ was not declared in this scope
   19 |     mac.Final(tag);
      |               ^~~
make[2]: *** [vanetza/security/CMakeFiles/security.dir/build.make:219: vanetza/security/CMakeFiles/security.dir/hmac.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:868: vanetza/security/CMakeFiles/security.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Maybe [this](https://www.cryptopp.com/wiki/Std::byte) is relevant? Changing `CryptoPP::byte` to just `byte` helps in this instance, however there is another problematic file `backend_cryptopp.cpp`. There is the same problem, furthermore, there is another undefined symbol `CryptoPP::VectorSource`:
```
/home/user/vanetza-security/xweissada/vanetza/vanetza/security/backend_cryptopp.cpp: In member function ‘bool vanetza::security::BackendCryptoPP::encrypt_aes(const ByteBuffer&, vanetza::security::MessageEncryptionParams::AES&)’:
/home/user/vanetza-security/xweissada/vanetza/vanetza/security/backend_cryptopp.cpp:185:19: error: ‘VectorSource’ is not a member of ‘CryptoPP’
  185 |         CryptoPP::VectorSource ss1(data, true,
      |                   ^~~~~~~~~~~~
/home/user/vanetza-security/xweissada/vanetza/vanetza/security/backend_cryptopp.cpp: In member function ‘bool vanetza::security::BackendCryptoPP::decrypt_aes(const ByteBuffer&, vanetza::security::MessageEncryptionParams::AES&)’:
/home/user/vanetza-security/xweissada/vanetza/vanetza/security/backend_cryptopp.cpp:206:19: error: ‘VectorSource’ is not a member of ‘CryptoPP’
  206 |         CryptoPP::VectorSource ss2(data, true,
      |                   ^~~~~~~~~~~~
make[2]: *** [vanetza/security/CMakeFiles/security.dir/build.make:544: vanetza/security/CMakeFiles/security.dir/backend_cryptopp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:868: vanetza/security/CMakeFiles/security.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

I was not able to fix  this. Including `#include <cryptopp/filters.h>` where VectorSource is declared did not help.
I have Crypto++ version 6 installed. My OS is Ubuntu 20.04.

During few days, I will try building using Ubuntu 22, where newer Crypto++ may be available.
I have not investigated this further as I expected to build without errors (I am using the base repository with all the example apps without problem).

**Comment by xweissada** [comment]
I tried rebuilding on Manjaro with Crypto++ version 8.9.0 and have no problems.

> Maybe [this](https://www.cryptopp.com/wiki/Std::byte) is relevant?

Yes, it seems like on your version of Crypto++, byte is still in the global namespace. According to the [documentation](https://cryptopp.com/docs/ref/config__int_8h.html#a0c8186d9b9b7880309c27230bbb5e69d), it should have been moved to the `CryptoPP` namespace in version 6.0, so I am unsure why you're still getting this error.

Regarding `CryptoPP::VectorSource`, this was introduced in Crypto++ 8.0, meaning to run v2cat version 8.0+ of Crypto++ is required. Ideally, this should be changed to match the Vanetza minimum version requirement for Crypto++ which is 5.6.1, of course.

**Comment by khevessy** [comment]
Right! Sorry. I had version 5.6.4, not 6. Problem solved, I built and installed latest Crypto++ from source.
If the recipe requires Crypto++ 8.0, I think it should have set this in the CMakeLists.txt [here](https://github.com/xweissada/vanetza/blob/c747d8abf17fcd9c53a734515968c55f9606afc4/CMakeLists.txt#L63), which wouldn't be compatible with the base repo as you say :-)
